import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    slug: "manikonda-residences",
    title: "MGR Manikonda Residences",
    shortDescription: "Bespoke luxury 3BHK family homes built for modern lifestyles, located in the serene residential heart of Manikonda.",
    description: "MGR Manikonda Residences is designed to be your family's personal sanctuary. Featuring wide cross-ventilated balconies, Vastu-compliant entry orientations, sun-lit family lounges, and premium teak finishes, this low-density development offers a peaceful retreat with immediate accessibility to West Hyderabad's IT corridor.",
    location: "Manikonda, Hyderabad",
    status: "Ongoing",
    progressPercent: 75,
    specs: {
      sizeRange: "1,850 - 2,450 Sq.Ft.",
      units: 25,
      floors: "5 Residential Floors",
      type: "Vastu-Compliant 3BHK Homes",
      approval: "HMDA & RERA Approved",
    },
    amenities: [
      "Lush Rooftop Landscaped Garden",
      "Modern Children's Play Zone",
      "Equipped Fitness Center",
      "100% Power Backup",
      "Premium Silent Elevators",
      "24/7 Smart CCTV Security",
      "EV Charging Infrastructure",
      "Intercom Facility",
    ],
    landmarks: [
      { name: "Lanco Hills Road", distance: "3 mins" },
      { name: "Delhi Public School", distance: "5 mins" },
      { name: "Continental Hospital", distance: "10 mins" },
      { name: "Hitec City & IKEA", distance: "12 mins" },
      { name: "Financial District", distance: "15 mins" },
    ],
    images: {
      exterior: "/uploads/projects/manikonda-residences/exterior.png",
      interior: "/uploads/projects/manikonda-residences/interior.webp",
      floorPlan: "/uploads/projects/manikonda-residences/floorplan.webp",
      amenities: "/uploads/projects/manikonda-residences/amenity.webp",
    },
    brochureUrl: "/brochures/manikonda-residences.pdf",
  },
  {
    slug: "platinum-enclave",
    title: "MGR Platinum Enclave",
    shortDescription: "Ultra-luxury gated community residences matching elite contemporary architectural design standards.",
    description: "Designed for families who settle for nothing less than absolute perfection, MGR Platinum Enclave in Tarnaka represents a legacy of refined living. These limited-edition homes feature expansive floor plates, soundproof windows, private foyer entrances, and premium Kohler bath finishes.",
    location: "Tarnaka, Hyderabad",
    status: "Launching",
    progressPercent: 15,
    specs: {
      sizeRange: "2,200 - 3,100 Sq.Ft.",
      units: 15,
      floors: "Exclusive 5-Story Block",
      type: "Luxury 3BHK & 4BHK Residences",
      approval: "HMDA Approved",
    },
    amenities: [
      "Rooftop Infinity Lounge",
      "Dedicated Double Car Parking",
      "Advanced Video Entry Security",
      "Solar-Fenced Boundary",
      "VRF Air Conditioning Pre-wiring",
      "Acoustic Glass Windows",
      "Kids Sand Pit & Activity Deck",
      "Automated Gate Entry System",
    ],
    landmarks: [
      { name: "Osmania Metro Station", distance: "4 mins" },
      { name: "Tarnaka Junction", distance: "5 mins" },
      { name: "Secunderabad Club", distance: "10 mins" },
      { name: "Secunderabad Station", distance: "12 mins" },
    ],
    images: {
      exterior: "/uploads/projects/platinum-enclave/exterior.png",
      interior: "/uploads/projects/platinum-enclave/interior.webp",
      floorPlan: "/uploads/projects/platinum-enclave/floorplan.webp",
      amenities: "/uploads/projects/platinum-enclave/amenity.webp",
    },
    brochureUrl: "/brochures/platinum-enclave.pdf",
  },
];
