import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    slug: "skyline-heights",
    title: "Skyline Heights",
    shortDescription: "Bespoke luxury 3BHK family residences designed for contemporary living in the heart of the Financial District.",
    description: "Skyline Heights represents the pinnacle of modern architectural design. Featuring expansive cross-ventilated balconies, Vastu-compliant layouts, sun-lit family lounges, and ultra-premium timber finishes, this exclusive low-density sanctuary delivers unmatched tranquility with immediate access to prime commercial corridors.",
    location: "Financial District, Hyderabad",
    status: "Ongoing",
    progressPercent: 75,
    specs: {
      sizeRange: "1,850 - 2,450 Sq.Ft.",
      units: 25,
      floors: "5 Residential Floors",
      type: "Vastu-Compliant 3BHK Homes",
      approval: "RERA Approved & Certified",
    },
    amenities: [
      "Lush Rooftop Landscaped Garden",
      "Modern Children's Play Zone",
      "Equipped Fitness Center",
      "100% Power Backup",
      "Premium Silent Elevators",
      "24/7 Smart CCTV Security",
      "EV Charging Infrastructure",
      "Intercom Facility",
    ],
    landmarks: [
      { name: "Commercial District Expressway", distance: "3 mins" },
      { name: "International Academy", distance: "5 mins" },
      { name: "Super-Specialty Medical Hub", distance: "10 mins" },
      { name: "Retail & Dining Galleria", distance: "12 mins" },
      { name: "Financial Hub Center", distance: "15 mins" },
    ],
    images: {
      exterior: "/uploads/projects/manikonda-residences/exterior.png",
      interior: "/uploads/projects/manikonda-residences/interior.webp",
      floorPlan: "/uploads/projects/manikonda-residences/floorplan.webp",
      amenities: "/uploads/projects/manikonda-residences/amenity.webp",
    },
    brochureUrl: "/brochures/skyline-heights.pdf",
  },
  {
    slug: "golden-horizon",
    title: "Golden Horizon",
    shortDescription: "Ultra-luxury gated enclave matching contemporary international architectural design standards.",
    description: "Designed for discerning families who demand absolute refinement, Golden Horizon in Green Valley embodies a legacy of timeless elegance. These limited-edition residences feature expansive floor plates, acoustic soundproof glazing, private foyer entrances, and luxury designer bath fittings.",
    location: "Green Valley, Hyderabad",
    status: "Launching",
    progressPercent: 15,
    specs: {
      sizeRange: "2,200 - 3,100 Sq.Ft.",
      units: 15,
      floors: "Exclusive 5-Story Block",
      type: "Luxury 3BHK & 4BHK Residences",
      approval: "Fully Approved Layout",
    },
    amenities: [
      "Rooftop Infinity Lounge",
      "Dedicated Double Car Parking",
      "Advanced Video Entry Security",
      "Solar-Fenced Boundary",
      "VRF Air Conditioning Pre-wiring",
      "Acoustic Glass Windows",
      "Kids Activity Deck",
      "Automated Gate Entry System",
    ],
    landmarks: [
      { name: "Central Transit Hub", distance: "4 mins" },
      { name: "Green Valley Plaza", distance: "5 mins" },
      { name: "Golf & Country Club", distance: "10 mins" },
      { name: "Main Terminal Station", distance: "12 mins" },
    ],
    images: {
      exterior: "/uploads/projects/platinum-enclave/exterior.png",
      interior: "/uploads/projects/platinum-enclave/interior.webp",
      floorPlan: "/uploads/projects/platinum-enclave/floorplan.webp",
      amenities: "/uploads/projects/platinum-enclave/amenity.webp",
    },
    brochureUrl: "/brochures/golden-horizon.pdf",
  },
];
